framework:
    router:
        # Utilisé pour générer des URLs quand il n'y a pas de requête HTTP
        # (ex : dans des commandes CLI, cron, workers, etc.)
        default_uri: '%env(DEFAULT_URI)%'

when@prod:
    framework:
        router:
            strict_requirements: null
